using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyProductAttribute("Ninject.Extensions.Logging: Logging Extension for Ninject")]
[assembly: AssemblyCompanyAttribute("Ninject Project Contributors")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2007-2012 Ninject Project Contributors and contributors")]
[assembly: AssemblyVersionAttribute("3.2.0.0")]
[assembly: AssemblyFileVersionAttribute("3.2.2.0")]
[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]

